apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: project-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: main-repo
  path: ./project/manifests
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
