apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: main-repo
  interval: 10m
  path: ./project/manifests
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
